import { useRef, useState, useMemo } from 'react';
import { useFrame, useLoader } from '@react-three/fiber';
import { Text } from '@react-three/drei';
import * as THREE from 'three';
import type { LearningContent } from './mockData';

interface ClassroomMonitorProps {
  position: [number, number, number];
  content: LearningContent & { imageUrl?: string };
  onClick?: () => void;
  isFocused?: boolean;
  scale?: number;
}

export function ClassroomMonitor({ position, content, onClick, isFocused, scale = 3 }: ClassroomMonitorProps) {
  const screenRef = useRef<THREE.Mesh>(null);
  const [flickerIntensity, setFlickerIntensity] = useState(1);
  const [isHovered, setIsHovered] = useState(false);
  const [imageLoaded, setImageLoaded] = useState(false);

  // Load image texture if available
  const imageTexture = useMemo(() => {
    if (content.imageUrl && content.imageUrl !== '/placeholder.svg') {
      const loader = new THREE.TextureLoader();
      const texture = loader.load(
        content.imageUrl,
        () => setImageLoaded(true),
        undefined,
        () => setImageLoaded(false)
      );
      texture.colorSpace = THREE.SRGBColorSpace;
      return texture;
    }
    return null;
  }, [content.imageUrl]);

  // CRT flicker effect
  useFrame((state) => {
    const flicker = 0.95 + Math.sin(state.clock.elapsedTime * 60) * 0.03 + Math.random() * 0.02;
    setFlickerIntensity(flicker);
  });

  const crtColor = "#3d3d3d";
  const screenGlow = isHovered && !isFocused ? "#2a6a2a" : "#1a4a1a";
  const hasImage = imageTexture && imageLoaded;

  return (
    <group
      position={position}
      rotation={[0, Math.PI / 2, 0]}
      scale={[scale, scale, scale]}
      onClick={(e) => {
        e.stopPropagation();
        onClick?.();
      }}
      onPointerEnter={() => setIsHovered(true)}
      onPointerLeave={() => setIsHovered(false)}
    >
      {/* Flat panel monitor body - slim modern style */}
      <mesh position={[0, 0, 0]} castShadow>
        <boxGeometry args={[1.8, 1.4, 0.15]} />
        <meshLambertMaterial color={crtColor} />
      </mesh>

      {/* Monitor bezel */}
      <mesh position={[0, 0, 0.06]}>
        <boxGeometry args={[1.7, 1.3, 0.05]} />
        <meshLambertMaterial color="#4a4a4a" />
      </mesh>

      {/* Screen - slightly inset */}
      <mesh ref={screenRef} position={[0, 0.05, 0.09]}>
        <planeGeometry args={[1.5, 1.1]} />
        <meshBasicMaterial
          color={hasImage ? "#ffffff" : screenGlow}
          transparent
          opacity={flickerIntensity}
        />
      </mesh>

      {/* Image display when available */}
      {hasImage && (
        <mesh position={[0, 0.05, 0.095]}>
          <planeGeometry args={[1.45, 1.05]} />
          <meshBasicMaterial
            map={imageTexture}
            transparent
            opacity={flickerIntensity * 0.95}
          />
        </mesh>
      )}

      {/* Screen content overlay - only show text when no image */}
      {!hasImage && (
        <group position={[0, 0.05, 0.095]}>
          {/* Title */}
          <Text
            position={[0, 0.3, 0]}
            fontSize={0.1}
            color="#33ff33"
            anchorX="center"
            anchorY="middle"
            font={undefined}
          >
            {content.title}
          </Text>

          {/* Formula */}
          <Text
            position={[0, 0.1, 0]}
            fontSize={0.12}
            color="#44ff44"
            anchorX="center"
            anchorY="middle"
            font={undefined}
          >
            {content.formula}
          </Text>

          {/* Example */}
          <Text
            position={[0, -0.1, 0]}
            fontSize={0.08}
            color="#66ff66"
            anchorX="center"
            anchorY="middle"
            font={undefined}
          >
            Example:
          </Text>
          <Text
            position={[0, -0.25, 0]}
            fontSize={0.1}
            color="#88ff88"
            anchorX="center"
            anchorY="middle"
            font={undefined}
          >
            {content.example}
          </Text>
        </group>
      )}

      {/* Image label when showing image */}
      {hasImage && (
        <Text
          position={[0, -0.5, 0.095]}
          fontSize={0.06}
          color="#33ff33"
          anchorX="center"
          anchorY="middle"
          font={undefined}
        >
          Generated by Tutor
        </Text>
      )}

      {/* Scanlines effect */}
      {Array.from({ length: 10 }).map((_, i) => (
        <mesh key={i} position={[0, -0.5 + i * 0.11, 0.096]}>
          <planeGeometry args={[1.5, 0.01]} />
          <meshBasicMaterial color="#000000" transparent opacity={0.08} />
        </mesh>
      ))}

      {/* Screen glow */}
      <pointLight
        position={[0, 0, 0.3]}
        intensity={0.3 * flickerIntensity}
        color={hasImage ? "#ffffff" : "#33ff33"}
        distance={2}
      />

      {/* Power LED */}
      <mesh position={[0.75, -0.55, 0.08]}>
        <circleGeometry args={[0.02, 8]} />
        <meshBasicMaterial color={hasImage ? "#00ffff" : "#00ff00"} />
      </mesh>
    </group>
  );
}
